In [1]:
#import 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

c:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "

In [3]:
Residential_data = pd.read_csv('RDC_Inventory_Core_Metrics_County_History.csv')

In [6]:
Residential_data.head()

,month_date_yyyymm,county_fips,county_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202403,48205,"hartley, tx",425000.0,0.1824,0.6915,12.0,-0.2500,-0.5102,161.0,...,444336.0,0.0990,0.3827,12.0,-0.2500,-0.5385,0.0833,NaN,0.0017,1.0
1,202403,27133,"rock, mn",309900.0,0.0376,0.2689,21.0,0.0244,-0.2500,53.0,...,397205.0,0.0321,0.2890,35.0,0.0145,0.1111,0.6190,-0.0395,0.2798,1.0
2,202403,40019,"carter, ok",199000.0,-0.0499,-0.0328,165.0,-0.0030,0.4865,61.0,...,306719.0,-0.0234,-0.0577,222.0,0.0207,0.2299,0.3576,0.0132,-0.2911,0.0
3,202403,42083,"mckean, pa",169000.0,-0.0663,0.3000,48.0,-0.0400,-0.1652,107.0,...,187270.0,-0.0467,0.2149,71.0,-0.1069,-0.1288,0.5208,-0.0892,0.1382,0.0
4,202403,1055,"etowah, al",248950.0,-0.0130,0.1609,236.0,0.0876,0.2826,50.0,...,296370.0,-0.0180,0.2054,303.0,0.0783,0.1744,0.2839,-0.0133,-0.1074,0.0